### ISSUE TITLE
Question regarding the task prompt

### ISSUE THREAD

**Issue by SiyuanHuang95** [zd11024/NaviLLM#1]
Thanks for your sharing! I have the following unclear questions:

1. How do you manage the task prompt, since I did not see the dataset implementation, I am wondering wether it is in the image-text interleave or something else?

2. How do represent the history? The embedding of the previous chosen images?

3. Is the keywords, like "Task", "History" also need to be encoded?

**Comment by zd11024** [comment]
Hi, thanks for your attention!
We have uploaded the paper at https://arxiv.org/abs/2312.02010. Please refer to the paper for details.

**Comment by SiyuanHuang95** [comment]
Yes, thanks for your info. TBH, I have read your paper, and then want to find some answers from your code.

And did your code in the current commit is complete, I did not see the dataset related stuff

**Comment by zd11024** [comment]
The code is complete. We are currently organizing the processed data and features, and plan to make them public soon.

1.  I manage the task prompt at models/prompt.py. We construct the specific prompt during the model execution.
2. Yes. The history is represented by the visual representations of the previously chosen viewpoints.
3. These keywords are also encoded into the task prompt. We provide the prompt in the appendix.

**Comment by SiyuanHuang95** [comment]
Thanks for your reply. I have one follow-up question: 

I am curious about how you constructed the "history_vis" in the batch, was that constructed offline? And How do set the history length? Do you apply some methods like sliding-window to do so?

**Comment by zd11024** [comment]
Following the previous work, we have set the maximum number of action rounds in `core/rollout.py'. You could modify this number in the config file.

And the `history_vis' is constructed at 
# https://github.com/zd11024/NaviLLM/blob/d5250014419170510e7a5004397c8e928013f750/core/rollout.py#L210

**Comment by SiyuanHuang95** [comment]
Got it. 

Thanks for your information!

**Comment by zd11024** [comment]
@SiyuanHuang95  Sorry. I just realized that I hadn't updated the 'datasets' folder. I have resolved this issue in the most recent commit #3 .
