### ISSUE TITLE
About navigation: are ``view points``  neccessary for LLM's input?

### ISSUE THREAD

**Issue by Yonggie** [zd11024/NaviLLM#10]
Hi, exellent work! 

It seems ``MP3DAgent``( the base agent class of all dataset)  highly relys on view points (and even graph map?) provided by the dataset? Any chance we get rid of the view points in a complete open scene?
![图片](https://github.com/zd11024/NaviLLM/assets/31330044/5a5d095a-1385-4296-b539-0bc733251eb5)

**Comment by zd11024** [comment]
Sorry for the late reply. Regarding your question, you could consider simulating in the [VLN-CE setting](https://github.com/jacobkrantz/VLN-CE), which has completely open scenes for exploration. I believe that by making some modifications to the simulator and action space, it is possible to achieve navigation without relying on viewpoints and graph.

**Comment by Yonggie** [comment]
gotcha
