### ISSUE TITLE
Missing connectivity folder and files from data

### ISSUE THREAD

**Issue by gmindflow** [zd11024/NaviLLM#11]
The connectivity folder and files are missing in the 'data' onedrive.
Are you suppose to copy the scan.txt file from Matterport3D dataset ?

**Comment by zd11024** [comment]
The connectivity folder can be found at [Matteport3D](https://github.com/peteanderson80/Matterport3DSimulator/tree/master). And I will add this directory to the shared folder.

**Comment by gmindflow** [comment]
Got it.
Thank you for your reply!
