### ISSUE TITLE
Error on non existing val_unseen split for LLaVA 

### ISSUE THREAD

**Issue by gmindflow** [zd11024/NaviLLM#12]
Hello, thank you for your great work!
While trying to reproduce the results of your work I am facing a small error here.

It looks like the error is coming from non existing key values of 'val_unseen' from the LLaVA split.
When I check config.LLaVA.SPLIT.keys(), the only dictionary key values that exist is 'train'.

Could you help me out with this? 
Are any files missing from the repository that are required to run this properly?

Thank you so much for your time!
![Screenshot 2024-06-05 at 11 20 44 PM](https://github.com/zd11024/NaviLLM/assets/102780751/464e2f07-5514-4485-b7b4-4406c4f7df28)

**Comment by zd11024** [comment]
In our project, we did not perform validation for LLaVA. When creating the dataloader, the construction of the val dataset for llava will be skipped. https://github.com/zd11024/NaviLLM/blob/e4f2bf118604d9dc30e34b40931288ec555a8b72/tasks/loaders.py#L24-L27

**Comment by gmindflow** [comment]
Sorry I forgot to mention which file I was running.
To give you more context of my problem: 
I got the error above while running `sh scripts/pretrain.sh`.

The error is brought up in the process of initializing val dataloaders.
When I check the `dataset_list` values in the process, it has `"r2r, reverie, cvdn, soon, scanqa, llava"`.
llava only having the 'train' value in the dictionary key is raising the error.

**Comment by zd11024** [comment]
Thanks for your feedback!  This is because `test_datasets` was not specified during pretraining. You can simply set `test_datasets` as `CVDN SOON R2R REVERIE ScanQA` or modify `loader.py` to skip the construction for the LLaVA's val loader. Here I suggest you directly run the script `multi_wo_pretrain.sh`, because we did not observe significant improvement after pretraining and it can greatly reduce the training time.

**Comment by gmindflow** [comment]
Okay got it!
I wanted to understand if it's an abnormal error or not and where it's coming from.
Seems like I have a clear understanding.

Thank you so much for your quick replies. Appreciate it! :)
