### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/lk/vln/NaviLLM/data/R2R/R2R_prevalent_aug_train_enc.jsonl'

### ISSUE THREAD

**Issue by LKlkun** [zd11024/NaviLLM#14]
Thanks for the work opening. When running  **sh scripts/pretrain.sh**  ,this error is reported，i check out the
 folder it seems that this file is missing.

**Comment by zd11024** [comment]
Thanks for your attention! We utilize the augmented data from [DUET](https://github.com/cshizhe/VLN-DUET?tab=readme-ov-file), you can directly download the augmented data at this [link](https://www.dropbox.com/scl/fo/4iaw2ii2z2iupu0yn4tqh/AJutXWSGTtjBFYXnxr-4YQw?rlkey=88khaszmvhybxleyv0a9bulyn&dl=0).
