### ISSUE TITLE
Missing Files: eqa_val_enc.json and eqa_answer_vocab.json in multi.yaml

### ISSUE THREAD

**Issue by YuehaoYin** [zd11024/NaviLLM#16]
Hi, I'm unable to find the files eqa_val_enc.json and eqa_answer_vocab.json mentioned in multi.yaml. Could you please guide me on how to obtain or generate these files? Thank you!

**Comment by zd11024** [comment]
We sincerely apologize for the loss of the EQA data during the machine migration process. Maybe you can use [OpenEQA](https://open-eqa.github.io/), which is the first open-vocabulary benchmark dataset for EQA supporting both episodic memory and active exploration use cases.
