### ISSUE TITLE
Questions about metric calculation of the test split 

### ISSUE THREAD

**Issue by tuin33** [zd11024/NaviLLM#18]
Hello, I've noticed that the gt_path of test scans in the annotation file R2R_test_enc.json only includes the start point. Could you please explain how the metrics, including SR, are calculated in this case? To be honest, my metrics of test split are not normal. OSR is 100% while SR is very low.
Thanks for your help!

**Comment by zd11024** [comment]
Because for the test split, the endpoint for a test case is not public. So you need to upload the JSON file of the predictions to [eval.ai](https://eval.ai/web/challenges/challenge-page/97/overview) for evaluation.
