### ISSUE TITLE
MatterPort 3D simulator

### ISSUE THREAD

**Issue by wusuoweima** [zd11024/NaviLLM#5]
[MatterPort 3D simulator](https://github.com/peteanderson80/Matterport3DSimulator) 和MatterPort 3D数据集对其他所有数据集/实验都是必须的吗

因为 onedrive 的数据我下载不到服务器上

**Comment by zd11024** [comment]
MatterPort 3D simulator是模拟器，仓库中提供的one drive链接数据对应不同的任务（存储具体的指令和轨迹），二者都是必须的。我可以稍后再上传一份数据到huggingface仓库，或者你可以先下载到本地再进行上传。

**Comment by wusuoweima** [comment]
只做一个数据集的前向推断 也需要下载所有吗？

**Comment by zd11024** [comment]
不需要的，你下载对应的数据集即可。但是需要下载相应的eva features。对于soon和reverie，可能还需要对应的obj_feature。

**Comment by zd11024** [comment]
我另外将数据上传到了https://huggingface.co/zd11024/NaviLLM/tree/main/data

**Comment by wusuoweima** [comment]
> 我另外将数据上传到了https://huggingface.co/zd11024/NaviLLM/tree/main/data

非常感谢
