### ISSUE TITLE
About the CUDA memory consumption

### ISSUE THREAD

**Issue by knightwzh** [zd11024/NaviLLM#6]
Thanks for your great work and there is a problem when I tried to run the code.
I notice that you mentioned the batch size is 64 on 8 A100 GPUs and in the script, the parameter "--batch_size" is 1 and "--gradient_accumulation_step" is 8. Does "batch is 64" means the actual batch size is 1 and it accumulates 8 times on 8 GPUs so the 64=1×8×8 ?
I raised this question because I attempted to run the code using RTX3090 with 24GB memory and found an issue with CUDA out of memory So if it's convenient, I would like to ask how much memory is used during your training, and if you think it's possible to run the code in 24GB of memory.
Could you please help me?

**Comment by zd11024** [comment]
Yes, the actual batch size is 1 and it accumulates 8 times on 8 GPUs so the 64=1×8×8.
I estimate that each GPU uses 60-70GB during training. So I think it's hard to run the code in 24GB of memory, maybe you could use some memory-efficient techniques such as LoRA and ZeRO3. I will try to add these features in the future.

**Comment by knightwzh** [comment]
Thanks for your quick response, I will have a try about some other techniques like you say.
