### ISSUE TITLE
CVDN dataset

### ISSUE THREAD

**Issue by KairosXu** [zd11024/NaviLLM#8]
Hello, thanks for your nice work!
While trying to pretrain the model, I met the following problem:

File "/root/mount/NaviLLM/tasks/datasets/cvdn.py", line 51, in load_data
    new_item['path'] = [item['start_pano']['pano']]
TypeError: string indices must be integers

So I check the original CVDN train dataset and find:
![image](https://github.com/zd11024/NaviLLM/assets/91948249/f36c54ff-2048-4b07-bc64-f7ccc4cee164)

Item is a python dict, and start_pano is its key, but the corresponding value is a string like "c1d33aa653f146dc8f13b6e713c7dc0e". So while acquiring its key 'pano', I got a mistake.

Have you reformat the CVDN dataset? Or could you offer me some suggestions to my problem? Hope for your reply soon!

**Comment by zd11024** [comment]
Hi, thanks for your attention!

We use the original dataset (refer to https://github.com/mmurray/cvdn/blob/master/tasks/NDH/data/download.sh). In addition, I've also uploaded the CVDN dataset to the onedrive link.

**Comment by KairosXu** [comment]
Thanks for your reply!
Following your previous instructions, I download the CVDN dataset from link [https://github.com/mmurray/cvdn/blob/master/tasks/CVDN/data/download.sh].

What's the difference between the two datasets? Cause it seems the the link above refers to the original CVDN dataset, according to the CVDN official repo.
<img width="999" alt="image" src="https://github.com/zd11024/NaviLLM/assets/91948249/50ec9fc5-b6d0-46f4-ac7d-444c572b0a4a">

Hope for your reply soon!

**Comment by KairosXu** [comment]
Thanks for your reply!
Following your previous instructions, I download the CVDN dataset from link [https://github.com/mmurray/cvdn/blob/master/tasks/CVDN/data/download.sh](https://github.com/mmurray/cvdn/blob/master/tasks/CVDN/data/download.sh).

What's the difference between the two datasets? Cause it seems that the the link above refers to the original CVDN dataset, according to the CVDN official repo.
<img width="1004" alt="image" src="https://github.com/zd11024/NaviLLM/assets/91948249/b4fa080f-478e-4da6-aab7-d6b52a70329a">

Hope for your reply soon! Thanks!

**Comment by zd11024** [comment]
NDH task requires the agent to navigate given the dialog history, while CVDN task asks the agent to chat with an oracle and navigate to the target location. Here we test our model on the NDH task.

**Comment by KairosXu** [comment]
Thanks for your reply! I'll try the dataset on NDH task.
