### ISSUE TITLE
No module named 'MatterSim'

### ISSUE THREAD

**Issue by Breezewrf** [zd11024/NaviLLM#9]
Hi,

Thank you for sharing your excellent work!

Could you tell me how to deal with the error "No module named 'MatterSim'", I set up the MatterSim in docker successfully, and I can only import the module in the terminal of docker. Should I build the MatterSim in real machine?
```
(navillm) root@18039d198356:~/mount/Matterport3DSimulator/navillm# export PYTHONPATH=/root/mount/Matterport3DSimulator/build:$PYTHONPATH
(navillm) root@18039d198356:~/mount/Matterport3DSimulator/navillm# python3
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MatterSim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'MatterSim'
KeyboardInterrupt
>>> 

(vlnduet) root@18039d198356:~/mount/Matterport3DSimulator/navillm# which python3
/root/miniconda3/envs/vlnduet/bin/python3
(vlnduet) root@18039d198356:~/mount/Matterport3DSimulator/navillm# conda deactivate
(base) root@18039d198356:~/mount/Matterport3DSimulator/navillm# which python3
/root/miniconda3/bin/python3
(base) root@18039d198356:~/mount/Matterport3DSimulator/navillm# conda deactivate
root@18039d198356:~/mount/Matterport3DSimulator/navillm# which python3
/usr/bin/python3
root@18039d198356:~/mount/Matterport3DSimulator/navillm# python3
Python 3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MatterSim
>>> 
```

Thank you!

**Comment by zd11024** [comment]
It seems a bit weird. We haven't done any environment configuration in Docker. Maybe you can check the MatterSim repository to see if there are any similar [issues.](https://github.com/peteanderson80/Matterport3DSimulator/issues)

**Comment by goodstudent9** [comment]
the python version of your conda env is not the same as cmakefile in MatterSim is the main reason I think

**Comment by lemonphoenix9** [comment]
One solution I came up with is to copy the two. so files compiled in the build folder to the site packages in your new environment. After trying, I found that 'import MatterSim' in other environments was successful!
